import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {build} from 'esbuild';
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');sqlite.exec(fs.readFileSync('drizzle/0000_aspiring_misty_knight.sql','utf8'));
let current={id:'owner',email:'owner@example.com'};
const query=(sql,args=[])=>({sql,args,bind(...v){return query(sql,v)},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){const r=sqlite.prepare(sql).run(...args);return {success:true,meta:{changes:r.changes}}}});
globalThis.__testEnv={DB:{prepare:query,async batch(jobs){sqlite.exec('BEGIN');try{const r=[];for(const j of jobs)r.push(await j.run());sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}}},BUCKET:{}};
globalThis.__testHeaders=()=>new Headers({'oai-authenticated-user-id':current.id,'oai-authenticated-user-email':current.email});
await build({entryPoints:['app/api/operations/route.ts'],bundle:true,platform:'node',format:'esm',outfile:'/tmp/depi-operations-test.mjs',plugins:[{name:'test-bindings',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers)$/},a=>({path:a.path,namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.__testEnv':'export const headers=async()=>globalThis.__testHeaders()',loader:'js'}))}}]});
const api=await import('/tmp/depi-operations-test.mjs');const post=async(action,x={})=>{const r=await api.POST(new Request('https://test.local/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...x})}));return await r.json()};
const check=async(action,x={})=>{const r=await post(action,x);assert.equal(r.error,undefined,r.error);return r};
test('full seeded backend workflow and permission gates',async()=>{
 await check('setup');assert.equal(sqlite.prepare('SELECT count(*) n FROM students').get().n,1000);assert.equal(sqlite.prepare('SELECT count(*) n FROM tasks').get().n,1000);
 const data=await (await api.GET()).json();assert.equal(data.students.length,1000);assert.equal(data.students[0].graduation,'0/3');assert.ok(data.students[0].next_task);
 let r=await post('contact',{student_id:'S10001'});assert.match(r.error,/incomplete/);
 sqlite.prepare('INSERT INTO attachments VALUES(?,?,?,?,?,?,?,?,?)').run('PROOF-1','S10001','key1','proof.png','image/png',100,'hash1','owner',new Date().toISOString());
 const c={student_id:'S10001',outcome:'Responded',proof_id:'PROOF-1',next_action:'Next contact',owner:'owner',due:'2027-01-01T00:00:00Z',occurred_at:new Date().toISOString(),channel:'WhatsApp',request_id:'contact-once'};
 await check('contact',c);await check('contact',c);assert.equal(sqlite.prepare("SELECT count(*) n FROM contacts WHERE student_id='S10001'").get().n,1);
 await check('account_request',{id:'REQ1',student_id:'S10001',task:'Banner',platform:'Khamsat',value:5});
 r=await post('allocate',{request:'REQ1',account:'ACC-102',task_fit:true});assert.match(r.error,/role/);
 await check('staff',{name:'Owner',email:'owner@example.com',roles:['Project Operations','Operations Systems / Admin','Higher Board'],reason:'Explicit test allocation role'});
 await check('allocate',{request:'REQ1',account:'ACC-102',task_fit:true});assert.equal(sqlite.prepare("SELECT status FROM accounts WHERE id='ACC-102'").get().status,'Assigned');
 await check('account_request',{id:'REQ2',student_id:'S10026',task:'Banner two',platform:'Khamsat',value:5});r=await post('allocate',{request:'REQ2',account:'ACC-102',task_fit:true});assert.match(r.error,/unavailable|assigned/);
 const gig=sqlite.prepare("SELECT * FROM gigs WHERE student_id='S10001'").get();r=await post('gig_transition',{id:gig.id,status:'Paid',proof_id:'PROOF-1',occurred_at:new Date().toISOString()});assert.match(r.error,/transition/);
 for(const status of ['Gig Opened','Work Submitted','Delivered','Paid'])await check('gig_transition',{id:gig.id,status,proof_id:'PROOF-1',occurred_at:new Date().toISOString()});
 await check('evidence',{id:'EV1',gig_id:gig.id,proof_id:'PROOF-1',source:'WhatsApp'});
 r=await post('review',{id:'EV1',notes:'Looks complete'});assert.match(r.error,/role/);
 current={id:'coach-login',email:'staff-coach@example.invalid'};await check('review',{id:'EV1',notes:'Coach confirms delivery'});
 current={id:'owner',email:'owner@example.com'};await check('review',{id:'EV1',notes:'Completeness checked'});
 r=await post('review',{id:'EV1',decision:'Accept',notes:'Approve'});assert.match(r.error,/role/);
 current={id:'quality-login',email:'staff-quality@example.invalid'};await check('review',{id:'EV1',decision:'Reject',code:'EV01',notes:'Need delivery screenshot',request_id:'reject-once'});await check('review',{id:'EV1',decision:'Reject',code:'EV01',notes:'Need delivery screenshot',request_id:'reject-once'});assert.equal(sqlite.prepare("SELECT count(*) n FROM tasks WHERE category='Correction'").get().n,1);
 current={id:'owner',email:'owner@example.com'};await check('review',{id:'EV1',proof_id:'PROOF-1',notes:'Corrected package'});
 current={id:'quality-login',email:'staff-quality@example.invalid'};await check('review',{id:'EV1',decision:'Accept',notes:'All seven checks passed',checklist:['Completeness','Identity','Delivery','Payment/value','Authenticity','Source consistency','Duplicate checks']});
 assert.equal(sqlite.prepare("SELECT status FROM evidence WHERE id='EV1'").get().status,'Accepted');assert.equal(sqlite.prepare("SELECT result FROM graduation_ledger WHERE student_id='S10001' ORDER BY rowid DESC LIMIT 1").get().result,'1/3');
 current={id:'coordinator-login',email:'staff-omar@example.invalid'};r=await post('contact',c);assert.ok(r.error);r=await post('review',{id:'EV1',decision:'Reopen',notes:'Unauthorized'});assert.ok(r.error);
 assert.throws(()=>sqlite.exec("UPDATE audit_events SET action='tampered'"),/immutable/);assert.throws(()=>sqlite.exec('DELETE FROM evidence_reviews'),/immutable/);
});
test('database allocation guard protects stale concurrent eligibility',()=>{const now=new Date().toISOString();assert.throws(()=>sqlite.prepare('INSERT INTO account_assignments VALUES(?,?,?,?,?,?)').run('ASN-late','ACC-102','S10026','G102','REQ2',now),/eligibility/)});
