export const roles=['Project Operations','Team Supervisor','Operations Coordinator','Coach','Coach Operations','Quality Member','Quality Lead','Higher Board','Operations Systems / Admin'];
export const controlledPlatforms=['Kafeel','Nafezly','Khamsat'];
export const policy={contactDays:7,coachHours:24,l1Hours:24,qualityHours:48,correctionDays:7,failedAttempts:5,failedWindowDays:14,target:85,minGig:5,gigCount:3,minTotal:15,largeGig:300,riskAttendance:70,criticalAttendance:50,journeyDelayedLag:1,journeyCriticalLag:2,milestoneWeek1:1,milestoneWeek2:2,milestoneWeek3:3,milestoneWeek4:4,milestoneWeek5:5,milestoneWeek6:6,milestoneWeek7:7,milestoneWeek8:8};
export function ensure(ok:unknown,message:string):asserts ok {if(!ok)throw new Error(message)}
export function graduation(gigs:any[],p=policy){const q=gigs.filter(g=>g.status==='Accepted'&&g.gig_status==='Paid').map(g=>({...g,qualified_value:g.currency==='USD'?Number(g.value):Number(g.usd_value)||0})).filter(g=>g.qualified_value>0);if(q.some(g=>g.qualified_value>=p.largeGig))return '$300 Graduate';const small=q.filter(g=>g.qualified_value>=p.minGig);return small.length>=p.gigCount&&small.reduce((s,g)=>s+g.qualified_value,0)>=p.minTotal?'Graduated':`${Math.min(small.length,2)}/3`;}
export const gigFlow=['Account Assigned','Gig Opened','Work Submitted','Delivered','Paid'];
export function nextGig(from:string,to:string,proof:boolean){ensure(proof,'Upload a screenshot before recording client activity.');ensure(['Cancelled','Failed'].includes(to)?!['Paid','Cancelled','Failed'].includes(from):gigFlow.indexOf(to)===gigFlow.indexOf(from)+1&&gigFlow.includes(from),'This gig transition is not allowed. Complete the current step first.');}
export function validateContact(x:any){for(const k of ['student_id','outcome','proof_id','next_action','owner','due','occurred_at','channel'])ensure(typeof x[k]==='string'&&x[k].trim(),`Contact is incomplete: ${k.replaceAll('_',' ')} is required.`);ensure(['Responded','No Response','Follow-Up Required','Problem Identified','Escalated'].includes(x.outcome),'Choose a valid contact outcome.');ensure(!Number.isNaN(Date.parse(x.due))&&!Number.isNaN(Date.parse(x.occurred_at)),'Dates must be valid.');ensure(Date.parse(x.occurred_at)<=Date.now()+60000,'Contact date cannot be in the future.');ensure(Date.parse(x.due)>=Date.parse(x.occurred_at),'The next action must be due after contact.');}
export function expectedMilestone(week:number,p:any=policy){return week<1?0:Number(p['milestoneWeek'+Math.min(8,week)]??Math.min(8,week));}
export function risk(s:any,week:number,attendance:number|null,failed:number,rejections:number,p:any=policy){const reasons:string[]=[];let status='Active';const lag=expectedMilestone(week,p)-s.milestone;if((attendance!==null&&attendance<p.riskAttendance)||!s.last_contact||Date.now()-Date.parse(s.last_contact)>p.contactDays*86400000||lag>=p.journeyDelayedLag){status='At Risk';if(attendance!==null&&attendance<p.riskAttendance)reasons.push(`Attendance ${attendance}%`);if(!s.last_contact||Date.now()-Date.parse(s.last_contact)>p.contactDays*86400000)reasons.push(`No valid contact in ${p.contactDays} days`);if(lag>=p.journeyDelayedLag)reasons.push(`${lag} milestone${lag===1?'':'s'} behind`);}if((attendance!==null&&attendance<p.criticalAttendance)||lag>=p.journeyCriticalLag||failed>=p.failedAttempts||rejections>=2){status='Critical';if(lag>=p.journeyCriticalLag)reasons.push('Two or more milestones behind');if(failed>=p.failedAttempts)reasons.push(`${p.failedAttempts} failed attempts in ${p.failedWindowDays} days`);if(rejections>=2)reasons.push('Second evidence rejection');}return{status,reasons};}
export function can(roleList:string[],allowed:string[]){return roleList.some(r=>allowed.includes(r))}
export const rejectionCodes=['EV01 Missing delivery proof','EV02 Missing/invalid payment proof','EV03 Identity/account mismatch','EV04 Value/graduation rule not met','EV05 Wrong controlled account/task','EV06 Duplicate gig/order/payment','EV07 Evidence incomplete/inconsistent','EV08 Work does not qualify','EV09 Suspected falsified/manipulated evidence','EV10 Platform/source inconsistency'];
export function csvCell(v:any){const x=String(v??'');return '"'+(/^[=+@\-\t\r]/.test(x)?"'"+x:x).replaceAll('"','""')+'"';}

export function validatePolicy(input:any){ensure(input&&typeof input==='object'&&!Array.isArray(input),'Provide a policy object.');for(const k of Object.keys(input))ensure(k in policy,`Unknown policy field: ${k}`);const p:any={...policy,...input};for(const k of Object.keys(policy))ensure(Number.isFinite(p[k])&&p[k]>0,`Invalid policy value: ${k}`);for(const k of ['failedAttempts','failedWindowDays','gigCount','journeyDelayedLag','journeyCriticalLag','milestoneWeek1','milestoneWeek2','milestoneWeek3','milestoneWeek4','milestoneWeek5','milestoneWeek6','milestoneWeek7','milestoneWeek8'])ensure(Number.isInteger(p[k]),`${k} must be a whole number.`);ensure(p.target<=100&&p.riskAttendance<=100&&p.criticalAttendance<=100,'Percentage thresholds cannot exceed 100.');ensure(p.criticalAttendance<=p.riskAttendance,'Critical attendance must not exceed the At Risk threshold.');ensure(p.largeGig>=p.minGig,'Large-gig threshold must be at least the minimum gig value.');ensure(p.journeyCriticalLag>=p.journeyDelayedLag,'Critical journey lag must not be lower than delayed journey lag.');for(let n=2;n<=8;n++)ensure(p['milestoneWeek'+n]>=p['milestoneWeek'+(n-1)],'Journey milestones must not move backwards.');return p;}
