export const roles=['Project Operations','Team Supervisor','Operations Coordinator','Coach','Coach Operations','Quality Member','Quality Lead','Higher Board','Operations Systems / Admin'];
export const policy={contactDays:7,coachHours:24,l1Hours:24,qualityHours:48,correctionDays:7,failedAttempts:5,failedWindowDays:14,target:85,minGig:5,gigCount:3,minTotal:15,largeGig:300,riskAttendance:70,criticalAttendance:50};
export function ensure(ok:unknown,message:string):asserts ok {if(!ok)throw new Error(message)}
export function graduation(gigs:any[],p=policy){const q=gigs.filter(g=>g.status==='Accepted'&&g.gig_status==='Paid'&&g.currency==='USD');if(q.some(g=>g.value>=p.largeGig))return '$300 Graduate';const small=q.filter(g=>g.value>=p.minGig);return small.length>=p.gigCount&&small.reduce((s,g)=>s+g.value,0)>=p.minTotal?'Graduated':`${Math.min(small.length,2)}/3`;}
export const gigFlow=['Account Assigned','Gig Opened','Work Submitted','Delivered','Paid'];
export function nextGig(from:string,to:string,proof:boolean){ensure(proof,'Upload a screenshot before recording client activity.');ensure(['Cancelled','Failed'].includes(to)?!['Paid','Cancelled','Failed'].includes(from):gigFlow.indexOf(to)===gigFlow.indexOf(from)+1&&gigFlow.includes(from),'This gig transition is not allowed. Complete the current step first.');}
export function validateContact(x:any){for(const k of ['student_id','outcome','proof_id','next_action','owner','due','occurred_at','channel'])ensure(typeof x[k]==='string'&&x[k].trim(),`Contact is incomplete: ${k.replaceAll('_',' ')} is required.`);ensure(['Responded','No Response','Follow-Up Required','Problem Identified','Escalated'].includes(x.outcome),'Choose a valid contact outcome.');ensure(!Number.isNaN(Date.parse(x.due))&&!Number.isNaN(Date.parse(x.occurred_at)),'Dates must be valid.');ensure(Date.parse(x.occurred_at)<=Date.now()+60000,'Contact date cannot be in the future.');ensure(Date.parse(x.due)>=Date.parse(x.occurred_at),'The next action must be due after contact.');}
export function risk(s:any,week:number,attendance:number|null,failed:number,rejections:number,p=policy){const reasons:string[]=[];let status='Active';if((attendance!==null&&attendance<p.riskAttendance)||!s.last_contact||Date.now()-Date.parse(s.last_contact)>p.contactDays*86400000){status='At Risk';if(attendance!==null&&attendance<p.riskAttendance)reasons.push(`Attendance ${attendance}%`);if(!s.last_contact||Date.now()-Date.parse(s.last_contact)>p.contactDays*86400000)reasons.push('No valid contact in 7 days');}if((attendance!==null&&attendance<p.criticalAttendance)||week-s.milestone>=2||failed>=p.failedAttempts||rejections>=2){status='Critical';if(week-s.milestone>=2)reasons.push('Two or more milestones behind');if(failed>=p.failedAttempts)reasons.push('Five failed attempts in 14 days');if(rejections>=2)reasons.push('Second evidence rejection');}return{status,reasons};}
export function can(roleList:string[],allowed:string[]){return roleList.some(r=>allowed.includes(r))}
export const rejectionCodes=['EV01 Missing delivery proof','EV02 Missing/invalid payment proof','EV03 Identity/account mismatch','EV04 Value/graduation rule not met','EV05 Wrong controlled account/task','EV06 Duplicate gig/order/payment','EV07 Evidence incomplete/inconsistent','EV08 Work does not qualify','EV09 Suspected falsified/manipulated evidence','EV10 Platform/source inconsistency'];
export function csvCell(v:any){const x=String(v??'');return '"'+(/^[=+@\-\t\r]/.test(x)?"'"+x:x).replaceAll('"','""')+'"';}
