import { env } from 'cloudflare:workers';
import { headers } from 'next/headers';
import { ensure,can,roles,policy,graduation,risk } from './domain/rules';
export function db(){ensure(env.DB,'The database is unavailable. Please try again shortly.');return env.DB;}
export function bucket(){ensure(env.BUCKET,'File storage is unavailable. Your changes have not been saved.');return env.BUCKET;}
export const now=()=>new Date().toISOString();export const uid=(p='EV')=>p+'-'+crypto.randomUUID();
export const stmt=(sql:string,...args:any[])=>db().prepare(sql).bind(...args);
export async function all(sql:string,...args:any[]){return (await stmt(sql,...args).all()).results as any[];}
export async function identity(){const h=await headers();const id=h.get('oai-authenticated-user-id');ensure(id,'Sign in with your staff account to continue.');return{id,email:h.get('oai-authenticated-user-email')||'',name:h.get('oai-authenticated-user-full-name')?decodeURIComponent(h.get('oai-authenticated-user-full-name')!):'Workspace owner'};}
export async function actor(){const i=await identity();const u:any=await stmt('SELECT * FROM users WHERE (id=? OR email=?) AND active=1',i.id,i.email).first();ensure(u,'Your account has not been added to this staff workspace. Ask an administrator for access.');return{...u,roles:JSON.parse(u.roles),scopes:JSON.parse(u.scopes)};}
export function permit(u:any,allowed:string[]){ensure(can(u.roles,allowed),'Your staff role does not permit this action.');}
export function scopeSql(u:any,alias='g'){if(can(u.roles,['Project Operations','Operations Systems / Admin','Quality Member','Quality Lead','Higher Board','Coach Operations']))return{sql:'1=1',args:[]};return{sql:`(${alias}.coordinator=? OR ${alias}.supervisor=? OR ${alias}.coach=?)`,args:[u.id,u.id,u.id]};}
export async function student(u:any,id:string){const q=scopeSql(u);const s:any=await stmt(`SELECT s.*,g.coordinator,g.supervisor,g.coach,g.policy_id FROM students s JOIN groups g ON g.id=s.group_id WHERE s.id=? AND ${q.sql}`,id,...q.args).first();ensure(s,'Student not found within your assigned scope.');return s;}
export async function proof(u:any,id:string,sid:string){const a:any=await stmt('SELECT * FROM attachments WHERE id=? AND student_id=?',id,sid).first();ensure(a,'Upload proof linked to this student first.');await student(u,sid);return a;}
export function auditStmt(u:any,action:string,entity:string,value:any,previous:any=null,requestId=uid('REQ'),reason:string|null=null){return stmt('INSERT INTO audit_events(id,actor,action,entity_id,previous,value,reason,request_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)',uid(),u.id,action,entity,previous?JSON.stringify(previous):null,JSON.stringify(value),reason,requestId,now());}
export async function recalc(sid:string){const s:any=await stmt('SELECT g.policy_id,p.config FROM students s JOIN groups g ON g.id=s.group_id JOIN policies p ON p.id=g.policy_id WHERE s.id=?',sid).first();const e=await all("SELECT e.id,e.status,g.status gig_status,g.value,g.currency FROM evidence e JOIN gigs g ON g.id=e.gig_id WHERE e.student_id=?",sid);const result=graduation(e,JSON.parse(s.config));await stmt('INSERT INTO graduation_ledger VALUES(?,?,?,?,?,?)',uid('GR'),sid,s.policy_id,result,JSON.stringify(e.filter(x=>x.status==='Accepted').map(x=>x.id)),now()).run();return result;}
export async function loadData(u:any){const q=scopeSql(u);const groups=await all(`SELECT g.*,c.name coordinator_name,s.name supervisor_name,h.name coach_name FROM groups g JOIN users c ON c.id=g.coordinator JOIN users s ON s.id=g.supervisor JOIN users h ON h.id=g.coach WHERE ${q.sql}`,...q.args);const students=await all(`SELECT s.*,g.track,g.provider,g.pathway,g.start_date,g.coordinator,g.supervisor,g.coach,c.name coordinator_name FROM students s JOIN groups g ON g.id=s.group_id JOIN users c ON c.id=g.coordinator WHERE ${q.sql}`,...q.args);const scoped=(table:string)=>all(`SELECT t.* FROM ${table} t JOIN students s ON s.id=t.student_id JOIN groups g ON g.id=s.group_id WHERE ${q.sql}`,...q.args);const [tasks,contacts,gigs,evidence,cases,attachments,requests,attendance]=await Promise.all(['tasks','contacts','gigs','evidence','cases','attachments','account_requests','attendance'].map(scoped));const studentIds=new Set(students.map(s=>s.id));const reviews=await all(`SELECT r.* FROM evidence_reviews r JOIN evidence e ON e.id=r.evidence_id JOIN students s ON s.id=e.student_id JOIN groups g ON g.id=s.group_id WHERE ${q.sql}`,...q.args);const sessions=await all(`SELECT t.* FROM sessions t JOIN groups g ON g.id=t.group_id WHERE ${q.sql}`,...q.args);const p=await all('SELECT * FROM policies');const policyMap=Object.fromEntries(p.map(p=>[p.id,JSON.parse(p.config)]));for(const s of students){const group=groups.find(g=>g.id===s.group_id);s.week=Math.max(0,Math.min(8,Math.floor((Date.now()-Date.parse(s.start_date))/604800000)+1));const a=attendance.filter(a=>a.student_id===s.id&&a.status!=='Excused');s.attendance=a.length?Math.round(100*a.filter(a=>['Present','Late'].includes(a.status)).length/a.length):null;s.graduation=graduation(evidence.filter(e=>e.student_id===s.id).map(e=>({...e,...{gig_status:gigs.find(g=>g.id===e.gig_id)?.status,value:gigs.find(g=>g.id===e.gig_id)?.value,currency:gigs.find(g=>g.id===e.gig_id)?.currency}})),policyMap[group.policy_id]);const failed=contacts.filter(c=>c.student_id===s.id&&c.outcome==='No Response'&&Date.now()-Date.parse(c.occurred_at)<=14*86400000).length;s.risk=risk(s,s.week,s.attendance,failed,Math.max(0,...evidence.filter(e=>e.student_id===s.id).map(e=>e.rejections)),policyMap[group.policy_id]);s.next_task=tasks.filter(t=>t.student_id===s.id&&t.status==='Open').sort((a,b)=>a.due.localeCompare(b.due))[0]||null;}
const broad=can(u.roles,['Project Operations','Operations Systems / Admin']);const logs=broad?await all('SELECT * FROM audit_events ORDER BY created_at DESC LIMIT 200'):await all('SELECT * FROM audit_events WHERE actor=? ORDER BY created_at DESC LIMIT 100',u.id);
return{user:u,students,groups,tasks,contacts,gigs,evidence,cases,attachments:attachments.map(({key,hash,...a})=>a),requests,attendance,reviews,sessions,accounts:can(u.roles,['Higher Board','Project Operations','Operations Systems / Admin'])?await all('SELECT id,label,platform,status,credits FROM accounts'):[],staff:await all('SELECT id,name,email,roles,scopes,active FROM users'),policies:p,audit:logs,roles,serverTime:now()};}
export function graduationStmt(sid:string){return stmt(`INSERT INTO graduation_ledger(id,student_id,policy_id,result,evidence_ids,calculated_at)
SELECT ?,s.id,g.policy_id,
CASE WHEN (SELECT count(*) FROM evidence e JOIN gigs z ON z.id=e.gig_id WHERE e.student_id=s.id AND e.status='Accepted' AND z.status='Paid' AND z.currency='USD' AND z.value>=json_extract(p.config,'$.largeGig'))>0 THEN '$300 Graduate'
WHEN (SELECT count(*) FROM evidence e JOIN gigs z ON z.id=e.gig_id WHERE e.student_id=s.id AND e.status='Accepted' AND z.status='Paid' AND z.currency='USD' AND z.value>=json_extract(p.config,'$.minGig'))>=json_extract(p.config,'$.gigCount') AND (SELECT coalesce(sum(z.value),0) FROM evidence e JOIN gigs z ON z.id=e.gig_id WHERE e.student_id=s.id AND e.status='Accepted' AND z.status='Paid' AND z.currency='USD' AND z.value>=json_extract(p.config,'$.minGig'))>=json_extract(p.config,'$.minTotal') THEN 'Graduated'
ELSE CAST(min(2,(SELECT count(*) FROM evidence e JOIN gigs z ON z.id=e.gig_id WHERE e.student_id=s.id AND e.status='Accepted' AND z.status='Paid' AND z.currency='USD' AND z.value>=json_extract(p.config,'$.minGig'))) AS TEXT)||'/3' END,
(SELECT json_group_array(e.id) FROM evidence e WHERE e.student_id=s.id AND e.status='Accepted'),?
FROM students s JOIN groups g ON g.id=s.group_id JOIN policies p ON p.id=g.policy_id WHERE s.id=?`,uid('GR'),now(),sid);}
