import { zipSync,strToU8,unzipSync,strFromU8 } from 'fflate';
import { csvCell,ensure } from './domain/rules';
export function toCSV(rows:any[]){const keys=Object.keys(rows[0]||{id:''});return[keys.map(csvCell).join(','),...rows.map(r=>keys.map(k=>csvCell(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])).join(','))].join('\r\n');}
const xml=(v:any)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function col(n:number){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
export function toXLSX(rows:any[]){const keys=Object.keys(rows[0]||{id:''});const data=[keys,...rows.map(r=>keys.map(k=>typeof r[k]==='object'?JSON.stringify(r[k]):r[k]))];const sheet='<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+data.map((row,i)=>`<row r="${i+1}">`+row.map((v,j)=>`<c r="${col(j)}${i+1}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`).join('')+'</row>').join('')+'</sheetData></worksheet>';return zipSync({'[Content_Types].xml':strToU8('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'),'_rels/.rels':strToU8('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'),'xl/workbook.xml':strToU8('<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Operations" sheetId="1" r:id="rId1"/></sheets></workbook>'),'xl/_rels/workbook.xml.rels':strToU8('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'),'xl/worksheets/sheet1.xml':strToU8(sheet)});}
export function parseCSV(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}ensure(!quote,'CSV contains an unclosed quoted field.');row.push(cell);if(row.some(Boolean))rows.push(row);return objects(rows);}
function objects(rows:string[][]){ensure(rows.length>0,'The spreadsheet is empty.');const keys=rows.shift()!.map(k=>k.trim().replace(/^\uFEFF/,''));ensure(new Set(keys).size===keys.length,'Column names must be unique.');return rows.map((r,i)=>Object.fromEntries(keys.map((k,j)=>[k,r[j]||''])));}
export async function readSheet(file:File){ensure(file.size<=4*1024*1024,'Import files must be smaller than 4 MB.');if(file.name.toLowerCase().endsWith('.csv'))return parseCSV(await file.text());ensure(file.name.toLowerCase().endsWith('.xlsx'),'Choose an XLSX or CSV file.');const parts=unzipSync(new Uint8Array(await file.arrayBuffer()),{filter:f=>f.originalSize<8*1024*1024&&(/xl\/(worksheets\/sheet1.xml|sharedStrings.xml)$/.test(f.name))});const parser=new DOMParser();const strings=parts['xl/sharedStrings.xml']?Array.from(parser.parseFromString(strFromU8(parts['xl/sharedStrings.xml']),'text/xml').getElementsByTagName('si')).map(s=>s.textContent||''):[];ensure(parts['xl/worksheets/sheet1.xml'],'Use a workbook with data on the first worksheet.');const doc=parser.parseFromString(strFromU8(parts['xl/worksheets/sheet1.xml']),'text/xml');const rows=Array.from(doc.getElementsByTagName('row')).map(row=>{const out:string[]=[];for(const c of Array.from(row.getElementsByTagName('c'))){ensure(!c.getElementsByTagName('f').length,'Import values only; replace spreadsheet formulas with their values first.');const ref=c.getAttribute('r')||'A1';let n=0;for(const ch of ref.replace(/[0-9]/g,''))n=n*26+ch.charCodeAt(0)-64;const v=c.getElementsByTagName('v')[0]?.textContent||'';out[n-1]=c.getAttribute('t')==='s'?strings[Number(v)]:c.getAttribute('t')==='inlineStr'?c.textContent||'':v;}return out;});return objects(rows);}
